drop table if exists Chains          cascade;
drop table if exists Hotel           cascade;
drop table if exists Employee        cascade;
drop table if exists Login           cascade;
drop table if exists RoomDescription cascade;
drop table if exists Room            cascade;
drop table if exists RoomUnavailable cascade;
drop table if exists Client          cascade;
drop table if exists Reserve         cascade;